README.md
docker_db_config/6.0.12/EXAConf
docker_db_config/6.0.13/EXAConf
docker_db_config/6.1.1/EXAConf
docker_db_config/6.1/EXAConf
docker_db_config/6.2.4/EXAConf
docker_db_config/6.2/EXAConf
src/cli/commands/spawn_test_environment.py
src/lib/test_environment/docker_db_test_environment_parameter.py
src/lib/test_environment/spawn_test_database.py
src/test/test_test_environment.py
src/test/utils.py
start-test-env
start-test-env-without-docker-runner

- Make the DB MemSize adjustable and set the new default size to 2 GiB
- Make more command line arguments optional and add overview about important arguments to README

Make the DB MemSize adjustable

---

src/lib/test_environment/abstract_spawn_test_environment.py
src/lib/test_environment/docker_container_copy.py
src/lib/test_environment/spawn_test_database.py

Additionally, it refactors the way how copy files or directories to
docker containers. See, docker_container_copy.py.

Provide container information on the host and in the test container

---

src/lib/logging/container_log_handler.py
src/lib/test_environment/database_waiters/wait_for_test_docker_database.py

- Fix logging of database startup log
- Fetching all logs after DB startup

Fix logging

---

src/lib/test_environment/abstract_spawn_test_environment.py
src/lib/test_environment/database_setup/bucketfs_sync_checker.py
src/lib/test_environment/database_setup/docker_db_log_based_bucket_sync_checker.py
src/lib/test_environment/database_setup/populate_data.py
src/lib/test_environment/database_setup/time_based_bucketfs_sync_waiter.py
src/lib/test_environment/database_setup/upload_exa_jdbc.py
src/lib/test_environment/database_setup/upload_file_to_db.py
src/lib/test_environment/database_setup/upload_virtual_schema_jdbc_adapter.py
src/lib/test_environment/database_waiters/db_container_log_thread.py
src/lib/test_environment/database_waiters/is_database_ready_thread.py
src/lib/test_environment/database_waiters/wait_for_external_database.py
src/lib/test_environment/database_waiters/wait_for_test_docker_database.py
src/lib/test_environment/parameter/spawn_test_environment_parameter.py
src/lib/test_environment/setup_external_database_host.py
src/lib/test_environment/spawn_test_database.py
src/lib/test_environment/spawn_test_environment.py
src/lib/test_environment/spawn_test_environment_with_docker_db.py
src/lib/test_environment/spawn_test_environment_with_external_db.py
src/test/utils.py

Replaced absolute module paths with relative module paths

---

README.md

- Add newly supported Exasol versions
- Add supported docker runtimes
- Include docker-runtime option

Update Readme to reflect recent changes

---

.github/workflows/main.yml
githooks/update_packaging.sh

Run all tests for all docker-db version only for master, pull requests and for commit with [run all tests]

---

exasol_integration_test_docker_environment/lib/docker/images/create/docker_image_analyze_task.py
exasol_integration_test_docker_environment/lib/docker/images/create/utils/docker_registry_image_checker.py
exasol_integration_test_docker_environment/lib/test_environment/setup_external_database_host.py
exasol_integration_test_docker_environment/lib/test_environment/spawn_test_database.py

Remove print statements or replace them with logging

---

.github/workflows/check_setup_py.yaml

Fix and activate check_setup_py github workflow

---

exasol_integration_test_docker_environment/cli/common.py
exasol_integration_test_docker_environment/lib/base/stoppable_base_task.py
exasol_integration_test_docker_environment/test/test_base_task.py

Fix printing of duplicated exceptions in case of a failure in a task multiple tasks depend on

---

exasol_integration_test_docker_environment/test/test_test_environment.py
exasol_integration_test_docker_environment/test/test_test_environment_db_disk_size.py
exasol_integration_test_docker_environment/test/test_test_environment_db_mem_size.py
exasol_integration_test_docker_environment/test/test_test_environment_docker_runtime.py
exasol_integration_test_docker_environment/test/test_test_environment_nameservers.py
exasol_integration_test_docker_environment/testing/utils.py
setup.py

Extract test/utils.py to testing/utils.py, such that only utils.py is available in the package and not the tests

---

doc/changes/changelog.md
doc/changes/changes_0.6.0.md
exasol_integration_test_docker_environment/cli/options/test_environment_options.py
exasol_integration_test_docker_environment/lib/data/database_info.py
exasol_integration_test_docker_environment/lib/test_environment/database_setup/populate_data.py
exasol_integration_test_docker_environment/lib/test_environment/setup_external_database_host.py
exasol_integration_test_docker_environment/lib/test_environment/spawn_test_container.py
exasol_integration_test_docker_environment/lib/test_environment/spawn_test_database.py
exasol_integration_test_docker_environment/test/test_test_container_reuse.py
exasol_integration_test_docker_environment/test/test_test_env_reuse.py
exasol_integration_test_docker_environment/test/utils/luigi_utils.py
exasol_integration_test_docker_environment/test/utils/process_spawn_utils.py
exasol_integration_test_docker_environment/test/utils/utils.py

#120 test data not populated if reuse database setup is set to true

---

doc/changes/changes_0.6.0.md
poetry.lock
pyproject.toml
setup.py

#126: Update urllib3 package

---

doc/changes/changes_0.6.0.md

Prepare documentation for release 0.6.0

---

doc/changes/changes_0.7.0.md
exasol_integration_test_docker_environment/lib/base/base_task.py
exasol_integration_test_docker_environment/test/test_base_task_cleanup.py

#25: Cleanup methods can be called multiple times

---

doc/changes/changes_0.7.0.md

#143 prepare release 0.7.0

---

doc/changes/changes_0.8.0.md
exasol_integration_test_docker_environment/test/test_find_free_port.py
exasol_integration_test_docker_environment/testing/exaslct_test_environment.py
exasol_integration_test_docker_environment/testing/utils.py

#152 fix bug where bucket and database forward port can be same

---

doc/changes/changes_0.8.0.md
exasol_integration_test_docker_environment/lib/test_environment/abstract_spawn_test_environment.py
exasol_integration_test_docker_environment/lib/test_environment/database_setup/populate_data.py
exasol_integration_test_docker_environment/lib/test_environment/database_waiters/is_database_ready_thread.py
exasol_integration_test_docker_environment/lib/test_environment/parameter/general_spawn_test_environment_parameter.py
exasol_integration_test_docker_environment/test/test_test_env_reuse.py
tests/Dockerfile
tests/requirements.txt

#150: Updated exaplus and jdbc for test environment and cleanup Dockerfile

---

doc/changes/changes_0.8.0.md
exasol_integration_test_docker_environment/cli/common.py
exasol_integration_test_docker_environment/lib/__init__.py

#141: Extract module name extraction into separate method

---

doc/changes/changes_0.8.0.md
exasol_integration_test_docker_environment/cli/commands/spawn_test_environment.py
exasol_integration_test_docker_environment/lib/docker/__init__.py

#162: Make sure that all docker function calls use docker credentials if possible

---

.github/workflows/publish_docker_runner.yml
doc/changes/changes_0.9.0.md

#175: Fixed docker push and allow docker push workflow for ci_test branch

---

doc/changes/changes_0.10.0.md

#209: Prepared release 0.10.0

---

doc/changes/changes_0.11.0.md

#218: Prepare release

---

doc/changes/changes_0.12.0.md
exasol_integration_test_docker_environment/test/test_test_environment_docker_runtime.py

#211 fix output of test docker test environment docker runtime invalid runtime given test

---

doc/changes/changes_0.12.0.md
exasol_integration_test_docker_environment/lib/base/task_dependency.py
exasol_integration_test_docker_environment/test/test_generate_graph_plot.py

fixes https://github.com/exasol/integration-test-docker-environment/issues/244
check https://github.com/exasol/integration-test-docker-environment/pull/229#discussion_r942988207 for problem

#244: Fixed bug in generate graph plot if task uses luigi.ListParameter

---

doc/changes/changes_1.1.0.md

Prepared release 1.1.0

---

doc/changes/changes_1.1.0.md

fixed release date

---

doc/changes/changelog.md
doc/changes/changes_1.2.0.md
doc/changes/changes_1.X.Y.md
pyproject.toml
setup.py

Add information about CVE-2022-42969 to changelog

---

error_code_config.yml

Add error_code_config.yml

---

doc/changes/changes_1.2.0.md

fixed release codename

---

.github/workflows/release.yaml
doc/changes/changelog.md
doc/changes/changes_1.4.0.md
doc/developer_guide/developer_guide.rst
pyproject.toml
setup.py

Fixes #51 
- Add github workflow to create GitHub and PYPI releases
- Add "Creating a Release" section to the developer guide
- Update changelog

Release integration test docker environment to pypi

---

.github/actions/prepare_poetry_env/action.yml
.github/workflows/release.yaml

Fix release workflow

---

doc/changes/changes_1.6.0.md
exasol_integration_test_docker_environment/lib/api/common.py
exasol_integration_test_docker_environment/lib/test_environment/database_setup/upload_file_to_db.py
exasol_integration_test_docker_environment/test/test_upload.py

Fix exist_file_in_bucketfs in UploadFileToBucketFS

---

.gitignore
doc/changes/changes_1.6.0.md
vagrant/Vagrantfile
vagrant/provisioning/dns.sh
vagrant/provisioning/install.sh
vagrant/provisioning/install_poetry.sh
vagrant/provisioning/resize-disk.sh

#311: Add vagrant setup

---

doc/changes/changes_1.6.0.md

#318: Add release date and summary to changelog

---

.gitignore
doc/changes/changelog.md
doc/changes/changes_1.7.1.md
docker_db_config_template/8.18.1/EXAConf
exasol_integration_test_docker_environment/docker_db_config/8.18.1/EXAConf
poetry.lock
pyproject.toml
test/integration/test_udf_execution.py

#351: Added test for UDF with builtin Script-Language Container and fixed it for Docker-DB 8.18.1

---

doc/changes/changes_2.0.0.md
exasol_integration_test_docker_environment/lib/base/db_os_executor.py
exasol_integration_test_docker_environment/lib/test_environment/database_setup/docker_db_log_based_bucket_sync_checker.py
exasol_integration_test_docker_environment/lib/test_environment/database_setup/find_exaplus_in_db_container.py
exasol_integration_test_docker_environment/lib/test_environment/database_setup/upload_file_to_db.py
exasol_integration_test_docker_environment/lib/test_environment/database_waiters/is_database_ready_thread.py
test/integration/conftest.py
test/integration/helpers.py
test/integration/test_bucketfs_upload.py
test/integration/test_cli_environment.py
test/integration/test_ssh_access.py

Replaced calls to DockerContainer.exec_run() to support SSH access alternatively

---

doc/changes/changes_2.0.0.md

Updated changes file

---

doc/changes/changelog.md
doc/changes/changes_4.0.0.md
doc/changes/unreleased.md

Prepare release 4.0.0

---

doc/changes/unreleased.md
doc/user_guide/user_guide.rst
docker_db_config_template/8.32.0/EXAConf
docker_db_config_template/8.32.0/init_db.sh
exasol_integration_test_docker_environment/cli/options/test_environment_options.py
exasol_integration_test_docker_environment/docker_db_config/8.32.0/EXAConf
exasol_integration_test_docker_environment/docker_db_config/8.32.0/init_db.sh

#467: Added Docker-DB 8.32.0

---

doc/changes/unreleased.md
exasol_integration_test_docker_environment/lib/base/base_task.py
exasol_integration_test_docker_environment/lib/base/docker_parameter.py
exasol_integration_test_docker_environment/lib/base/flavor_task.py
exasol_integration_test_docker_environment/lib/docker/images/clean/clean_images.py
exasol_integration_test_docker_environment/lib/docker/images/create/docker_image_create_task.py
exasol_integration_test_docker_environment/lib/docker/images/create/docker_image_creator_base_task.py
exasol_integration_test_docker_environment/lib/docker/images/push/docker_image_push_base_task.py
exasol_integration_test_docker_environment/lib/docker/images/push/docker_push_parameter.py
exasol_integration_test_docker_environment/lib/docker/images/save/docker_image_save_base_task.py
exasol_integration_test_docker_environment/lib/models/config/build_config.py
exasol_integration_test_docker_environment/lib/models/config/docker_config.py
exasol_integration_test_docker_environment/lib/models/config/log_config.py
exasol_integration_test_docker_environment/lib/models/data/database_credentials.py
exasol_integration_test_docker_environment/lib/test_environment/abstract_spawn_test_environment.py
exasol_integration_test_docker_environment/lib/test_environment/create_certificates/analyze_certificate_container.py
exasol_integration_test_docker_environment/lib/test_environment/create_certificates/create_ssl_certificates_task.py
exasol_integration_test_docker_environment/lib/test_environment/database_setup/populate_data.py
exasol_integration_test_docker_environment/lib/test_environment/database_waiters/wait_for_external_database.py
exasol_integration_test_docker_environment/lib/test_environment/database_waiters/wait_for_test_docker_database.py
exasol_integration_test_docker_environment/lib/test_environment/parameter/docker_db_test_environment_parameter.py
exasol_integration_test_docker_environment/lib/test_environment/parameter/external_test_environment_parameter.py
exasol_integration_test_docker_environment/lib/test_environment/parameter/general_spawn_test_environment_parameter.py
exasol_integration_test_docker_environment/lib/test_environment/prepare_network_for_test_environment.py
exasol_integration_test_docker_environment/lib/test_environment/setup_external_database_host.py
exasol_integration_test_docker_environment/lib/test_environment/spawn_test_container.py
exasol_integration_test_docker_environment/lib/test_environment/spawn_test_database.py
exasol_integration_test_docker_environment/lib/test_environment/spawn_test_environment.py
exasol_integration_test_docker_environment/test/test_docker_build_base.py
pyproject.toml

#452: Use luigi mypy plugin for luigi parameters

---

test/integration/test_api_push_test_container.py

#474: Converted test_api_push_test_container.py to pytest

---

exasol_integration_test_docker_environment/test/test_api_test_environment.py
exasol_integration_test_docker_environment/testing/api_test_environment_context_provider.py
exasol_integration_test_docker_environment/testing/cli_test_environment_context_provider.py
exasol_integration_test_docker_environment/testing/utils.py
noxfile.py
test/integration/conftest.py
test/integration/helpers.py
test/integration/test_api_external_test_environment.py
test/integration/test_api_test_environment.py
test/integration/test_api_test_environment_with_custom_runtime_mapping.py
test/integration/test_ssh_access.py

#474: Converted test_api_test_environment.py to pytest

---

doc/user_guide/user_guide.rst
test/integration/docker_runtime/test_api_test_environment_custom_docker_runtime.py

Proposal for PR #481

---

doc/user_guide/user_guide.rst
exasol_integration_test_docker_environment/testing/api_test_environment_context_provider.py
exasol_integration_test_docker_environment/testing/utils.py
test/integration/conftest.py
test/integration/docker_runtime/common.py
test/integration/docker_runtime/test_api_test_environment_custom_docker_runtime.py
test/integration/docker_runtime/test_api_test_environment_default_docker_runtime.py
test/integration/docker_runtime/test_api_test_environment_invalid_docker_runtime.py

#474: Converted test api test environment docker runtime to pytest

---

test/integration/base_task/base_task.py
test/integration/base_task/test_base_task_cleanup.py
test/integration/base_task/test_collect_failures_diffrent_task_fail.py
test/integration/base_task/test_collect_failures_one_task_fails_but_is_dependency_of_multiple.py
test/integration/base_task/test_common_parameter.py
test/integration/base_task/test_dependency_creation.py
test/integration/base_task/test_failing_task.py
test/integration/base_task/test_json_pickle_parameter.py
test/integration/test_base_task_cleanup.py

#474: Converted test_base_task_cleanup.py to pytest

---

test/integration/conftest.py
test/integration/docker_runtime/test_api_test_environment_default_docker_runtime.py
test/integration/test_api_external_test_environment.py
test/integration/test_api_test_environment.py
test/integration/test_api_test_environment_certificate.py
test/integration/test_api_test_environment_with_custom_runtime_mapping.py
test/integration/test_cli_environment.py
test/integration/test_ssh_access.py
test/integration/test_udf_execution.py

#474: Converted test api test environment certificate to pytest

---

.github/workflows/build-and-publish.yml
.github/workflows/check-release-tag.yml
.github/workflows/checks.yml
.github/workflows/fast-tests.yml
.github/workflows/get-exasol-versions.yml
.github/workflows/gh-pages.yml
.github/workflows/matrix-python.yml
.github/workflows/report.yml
.github/workflows/test-db-versions-all-tests.yml
.github/workflows/test-db-versions-minimal.yml
.github/workflows/test-exaconf-files.yml
.github/workflows/test-python-versions.yml
doc/changes/unreleased.md
poetry.lock

#488: Updated dependencies

---

doc/changes/unreleased.md
exasol_integration_test_docker_environment/test/test_click_api_consistency.py
poetry.lock
pyproject.toml
test/unit/cli/cli_runner.py
test/unit/cli/test_health.py
test/unit/cli/test_spawn_test_environment.py
test/unit/test_click_api_consistency.py

related to #501: Converted integration API test to pytest - test_click_api_consistency

#501: Converted integration API test to pytest - test_click_api_consistency

---

doc/changes/unreleased.md
test/integration/test_gpu.py

#515: Update GPU Test Query

---

doc/changes/unreleased.md
exasol_integration_test_docker_environment/test/test_environment_variable.py
test/integration/test_api_test_environment_environment_variable.py

related to #522: Converted integration API test to pytest - test_environment_variable.py

#522: Converted integration API test to pytest - test_environment_variable.py
